  application: limhenryxyz
  version: 1
  runtime: python27
  api_version: 1
  threadsafe: yes

  handlers:
  - url: /
    static_files: public/landing/index.html
    upload: public/landing/index.html

  - url: /index.html
    static_files: public/landing/index.html
    upload: public/landing/index.html
    http_headers:
      Vary: Accept-Encoding

  - url: /cache-config.json
    static_files: public/landing/cache-config.json
    upload: public/landing/cache-config.json

  - url: /project.*
    static_files: public/landing/index.html
    upload: public/landing/index.html

  - url: /contact.*
    static_files: public/landing/index.html
    upload: public/landing/index.html

  - url: /resources.*
    static_files: public/landing/index.html
    upload: public/landing/index.html

  - url: /bower_components/(.+)
    static_files: public/bower_components/\1
    upload: public/bower_components/(.*)    
    http_headers:
      Vary: Accept-Encoding

  - url: /elements/(.+)
    static_files: public/landing/elements/\1
    upload: public/landing/elements/(.*)
    http_headers:
      Vary: Accept-Encoding

  - url: /data/(.+)
    static_files: public/landing/data/\1
    upload: public/landing/data/(.*)

  - url: /img/(.+)
    static_files: public/landing/img/\1
    upload: public/landing/img/(.*) 
          
  - url: /sw-import.js
    static_files: public/landing/sw-import.js
    upload: public/landing/sw-import.js  

  - url: /manifest.json
    static_files: public/landing/manifest.json
    upload: public/landing/manifest.json

  - url: /app.js
    static_files: public/landing/app.js
    upload: public/landing/app.js      

  - url: /bulletin
    static_files: public/bulletin/index.html
    upload: public/bulletin/index.html   

  - url: /bulletin/
    static_files: public/bulletin/index.html
    upload: public/bulletin/index.html   

  - url: /bulletin/(.+)
    static_files: public/bulletin/\1
    upload: public/bulletin/(.*)    

  - url: /slide
    static_files: public/slide/index.html
    upload: public/slide/index.html   

  - url: /slide/
    static_files: public/slide/index.html
    upload: public/slide/index.html   

  - url: /slide/(.+)
    static_files: public/slide/\1
    upload: public/slide/(.*)       

  - url: /rejected
    static_files: public/rejected/index.html
    upload: public/rejected/index.html      

  - url: /rejected/
    static_files: public/rejected/index.html
    upload: public/rejected/index.html   

  - url: /rejected/(.+)
    static_files: public/rejected/\1
    upload: public/rejected/(.*)      

  - url: /tmwifi
    static_files: public/tmwifi/index.html
    upload: public/tmwifi/index.html      

  - url: /tmwifi/
    static_files: public/tmwifi/index.html
    upload: public/tmwifi/index.html   

  - url: /tmwifi/(.+)
    static_files: public/tmwifi/\1
    upload: public/tmwifi/(.*)           

  - url: /blog/
    static_files: public/blog/index.html
    upload: public/blog/index.html   

  - url: /blog/(.+)
    static_files: public/blog/\1
    upload: public/blog/(.*)          

  - url: /chat
    static_files: public/chat/index.html
    upload: public/chat/index.html      

  - url: /chat/
    static_files: public/chat/index.html
    upload: public/chat/index.html   

  - url: /chat/(.+)
    static_files: public/chat/\1
    upload: public/chat/(.*)    

  - url: /gtav
    static_files: public/gtav/index.html
    upload: public/gtav/index.html      

  - url: /gtav/
    static_files: public/gtav/index.html
    upload: public/gtav/index.html   

  - url: /gtav/(.+)
    static_files: public/gtav/\1
    upload: public/gtav/(.*)   

  - url: /converter/download
    static_files: public/converter/download/index.html
    upload: public/converter/download/index.html      

  - url: /converter/download/
    static_files: public/converter/download/index.html
    upload: public/converter/download/index.html   

  - url: /converter/download/(.+)
    static_files: public/converter/download/\1
    upload: public/converter/download/(.*)      


  - url: /converter/web
    static_files: public/converter/web/index.html
    upload: public/converter/web/index.html      

  - url: /converter/web/
    static_files: public/converter/web/index.html
    upload: public/converter/web/index.html   

  - url: /converter/web/(.+)
    static_files: public/converter/web/\1
    upload: public/converter/web/(.*)      


  - url: /converter/faq
    static_files: public/converter/faq/index.html
    upload: public/converter/faq/index.html      

  - url: /converter/faq/
    static_files: public/converter/faq/index.html
    upload: public/converter/faq/index.html   

  - url: /converter/faq/(.+)
    static_files: public/converter/faq/\1
    upload: public/converter/faq/(.*)       


  - url: /converter
    static_files: public/converter/index.html
    upload: public/converter/index.html      

  - url: /converter/
    static_files: public/converter/index.html
    upload: public/converter/index.html   

  - url: /converter/(.+)
    static_files: public/converter/\1
    upload: public/converter/(.*)     

                           

  - url: /.*
    static_files: public/404.html
    upload: public/404.html        


  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?