  application: limhenryxyz
  version: 1
  runtime: python27
  api_version: 1
  threadsafe: yes

  handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html
    secure: always

  - url: /project.*
    static_files: public/index.html
    upload: public/index.html

  - url: /contact.*
    static_files: public/index.html
    upload: public/index.html

  - url: /resources.*
    static_files: public/index.html
    upload: public/index.html        

  - url: /bower_components/(.+)
    static_files: public/bower_components/\1
    upload: public/bower_components/(.*)    

  - url: /elements/(.+)
    static_files: public/elements/\1
    upload: public/elements/(.*)

  - url: /data/(.+)
    static_files: public/data/\1
    upload: public/data/(.*)

  - url: /img/(.+)
    static_files: public/img/\1
    upload: public/img/(.*) 

  - url: /elements.html
    static_files: public/elements.html
    upload: public/elements.html       
    
  - url: /sw-import.js
    static_files: public/sw-import.js
    upload: public/sw-import.js  

  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?