  runtime: python27
  api_version: 1
  threadsafe: true

  libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest

  handlers:

  - url: /data/(.+)
    static_files: public/landing/build/default/data/\1
    upload: public/landing/build/default/data/(.*)       

  - url: /bower_components/(.+)
    static_files: public/landing/build/default/bower_components/\1
    upload: public/landing/build/default/bower_components/(.*)       

  - url: /src/(.+)
    static_files: public/landing/build/default/src/\1  
    upload: public/landing/build/default/src/(.*)     

  - url: /images/(.+)
    static_files: public/landing/build/default/images/\1
    upload: public/landing/build/default/images/(.*) 

  - url: /manifest.json
    static_files: public/landing/build/default/manifest.json
    upload: public/landing/build/default/manifest.json

  - url: /service-worker.js
    static_files: public/landing/build/default/service-worker.js
    upload: public/landing/build/default/service-worker.js
    expiration: "0m"
    http_headers:
      Vary: Accept-Encoding
      service-worker-allowed: /

  - url: /blog.*
    static_files: public/blog/index.html
    upload: public/blog/index.html     

  - url: /rejected
    static_files: public/rejected/index.html
    upload: public/rejected/index.html      

  - url: /rejected/
    static_files: public/rejected/index.html
    upload: public/rejected/index.html   

  - url: /rejected/(.+)
    static_files: public/rejected/\1
    upload: public/rejected/(.*)      

  - url: /tmwifi
    static_files: public/tmwifi/index.html
    upload: public/tmwifi/index.html      

  - url: /tmwifi/
    static_files: public/tmwifi/index.html
    upload: public/tmwifi/index.html   

  - url: /tmwifi/(.+)
    static_files: public/tmwifi/\1
    upload: public/tmwifi/(.*)           

  - url: /chat
    static_files: public/chat/index.html
    upload: public/chat/index.html      

  - url: /chat/
    static_files: public/chat/index.html
    upload: public/chat/index.html   

  - url: /chat/(.+)
    static_files: public/chat/\1
    upload: public/chat/(.*)    

  - url: /gtav
    static_files: public/gtav/index.html
    upload: public/gtav/index.html      

  - url: /gtav/
    static_files: public/gtav/index.html
    upload: public/gtav/index.html   

  - url: /gtav/(.+)
    static_files: public/gtav/\1
    upload: public/gtav/(.*)   

  - url: /converter/download
    static_files: public/converter/download/index.html
    upload: public/converter/download/index.html      

  - url: /converter/download/
    static_files: public/converter/download/index.html
    upload: public/converter/download/index.html   

  - url: /converter/download/(.+)
    static_files: public/converter/download/\1
    upload: public/converter/download/(.*)      

  - url: /converter/web
    static_files: public/converter/web/index.html
    upload: public/converter/web/index.html      

  - url: /converter/web/
    static_files: public/converter/web/index.html
    upload: public/converter/web/index.html   

  - url: /converter/web/(.+)
    static_files: public/converter/web/\1
    upload: public/converter/web/(.*)      

  - url: /converter/faq
    static_files: public/converter/faq/index.html
    upload: public/converter/faq/index.html      

  - url: /converter/faq/
    static_files: public/converter/faq/index.html
    upload: public/converter/faq/index.html   

  - url: /converter/faq/(.+)
    static_files: public/converter/faq/\1
    upload: public/converter/faq/(.*)       

  - url: /converter
    static_files: public/converter/index.html
    upload: public/converter/index.html      

  - url: /converter/
    static_files: public/converter/index.html
    upload: public/converter/index.html   

  - url: /converter/(.+)
    static_files: public/converter/\1
    upload: public/converter/(.*)     

  - url: /bulletin
    script: bulletin.app  

  - url: /bulletin/
    script: bulletin.app  

  - url: /bulletin/(.+)
    script: bulletin.app

  - url: /slide
    script: slide.app  

  - url: /slide/
    script: slide.app  

  - url: /slide/(.+)
    script: slide.app

  - url: /
    static_files: public/landing/build/default/index.html
    upload: public/landing/build/default/index.html

  - url: /talks.*
    static_files: public/landing/build/default/index.html
    upload: public/landing/build/default/index.html    

  - url: /awards.*
    static_files: public/landing/build/default/index.html
    upload: public/landing/build/default/index.html       

  - url: /projects.*
    static_files: public/landing/build/default/index.html
    upload: public/landing/build/default/index.html      

  - url: /.*
    static_files: public/landing/build/default/index.html       
    upload: public/landing/build/default/index.html       

  skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?